// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: api/mr.proto

package mr_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Woker sends this message to Master in order to get a task and teach worker id.
type TaskRequestArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId uint64 `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
}

func (x *TaskRequestArgs) Reset() {
	*x = TaskRequestArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequestArgs) ProtoMessage() {}

func (x *TaskRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_mr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequestArgs.ProtoReflect.Descriptor instead.
func (*TaskRequestArgs) Descriptor() ([]byte, []int) {
	return file_api_mr_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequestArgs) GetWorkerId() uint64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

// Master sends this message to Worker and Worker knows task's detail.
type TaskRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	TaskId   uint64 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType []byte `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
}

func (x *TaskRequestResponse) Reset() {
	*x = TaskRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequestResponse) ProtoMessage() {}

func (x *TaskRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequestResponse.ProtoReflect.Descriptor instead.
func (*TaskRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_mr_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRequestResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TaskRequestResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRequestResponse) GetTaskType() []byte {
	if x != nil {
		return x.TaskType
	}
	return nil
}

// Worker sends this message to know the number of reduce worker.
type GetnReduceRequestArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetnReduceRequestArgs) Reset() {
	*x = GetnReduceRequestArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetnReduceRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetnReduceRequestArgs) ProtoMessage() {}

func (x *GetnReduceRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_mr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetnReduceRequestArgs.ProtoReflect.Descriptor instead.
func (*GetnReduceRequestArgs) Descriptor() ([]byte, []int) {
	return file_api_mr_proto_rawDescGZIP(), []int{2}
}

// Master sends the number of nreduce to Worker.
type GetnReduceRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NReduce uint64 `protobuf:"varint,1,opt,name=n_reduce,json=nReduce,proto3" json:"n_reduce,omitempty"`
}

func (x *GetnReduceRequestResponse) Reset() {
	*x = GetnReduceRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetnReduceRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetnReduceRequestResponse) ProtoMessage() {}

func (x *GetnReduceRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetnReduceRequestResponse.ProtoReflect.Descriptor instead.
func (*GetnReduceRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_mr_proto_rawDescGZIP(), []int{3}
}

func (x *GetnReduceRequestResponse) GetNReduce() uint64 {
	if x != nil {
		return x.NReduce
	}
	return 0
}

// Worker sends this message in order to report task's status.
type ReportTaskArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId uint64 `protobuf:"varint,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskType []byte `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
}

func (x *ReportTaskArgs) Reset() {
	*x = ReportTaskArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskArgs) ProtoMessage() {}

func (x *ReportTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_api_mr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskArgs.ProtoReflect.Descriptor instead.
func (*ReportTaskArgs) Descriptor() ([]byte, []int) {
	return file_api_mr_proto_rawDescGZIP(), []int{4}
}

func (x *ReportTaskArgs) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ReportTaskArgs) GetWorkerId() uint64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *ReportTaskArgs) GetTaskType() []byte {
	if x != nil {
		return x.TaskType
	}
	return nil
}

// Master sends this message and Worker knows whether it can exit or not.
type ReportTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanExit bool `protobuf:"varint,1,opt,name=can_exit,json=canExit,proto3" json:"can_exit,omitempty"`
}

func (x *ReportTaskResponse) Reset() {
	*x = ReportTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskResponse) ProtoMessage() {}

func (x *ReportTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_mr_proto_rawDescGZIP(), []int{5}
}

func (x *ReportTaskResponse) GetCanExit() bool {
	if x != nil {
		return x.CanExit
	}
	return false
}

var File_api_mr_proto protoreflect.FileDescriptor

var file_api_mr_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x2e, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x17,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x22, 0x36, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x6e, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x22,
	0x63, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x2f, 0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61,
	0x6e, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61,
	0x6e, 0x45, 0x78, 0x69, 0x74, 0x32, 0xe2, 0x01, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x2e, 0x6d, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1a, 0x2e, 0x6d, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x6e,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x41, 0x72, 0x67, 0x73, 0x1a, 0x20, 0x2e, 0x6d, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x6e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x15, 0x2e, 0x6d, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x19, 0x2e,
	0x6d, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x61, 0x7a, 0x75, 0x6b, 0x69, 0x2d,
	0x59, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mr_proto_rawDescOnce sync.Once
	file_api_mr_proto_rawDescData = file_api_mr_proto_rawDesc
)

func file_api_mr_proto_rawDescGZIP() []byte {
	file_api_mr_proto_rawDescOnce.Do(func() {
		file_api_mr_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mr_proto_rawDescData)
	})
	return file_api_mr_proto_rawDescData
}

var file_api_mr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_mr_proto_goTypes = []interface{}{
	(*TaskRequestArgs)(nil),           // 0: mr.v1.TaskRequestArgs
	(*TaskRequestResponse)(nil),       // 1: mr.v1.TaskRequestResponse
	(*GetnReduceRequestArgs)(nil),     // 2: mr.v1.GetnReduceRequestArgs
	(*GetnReduceRequestResponse)(nil), // 3: mr.v1.GetnReduceRequestResponse
	(*ReportTaskArgs)(nil),            // 4: mr.v1.ReportTaskArgs
	(*ReportTaskResponse)(nil),        // 5: mr.v1.ReportTaskResponse
}
var file_api_mr_proto_depIdxs = []int32{
	0, // 0: mr.v1.MapReduce.TaskRequest:input_type -> mr.v1.TaskRequestArgs
	2, // 1: mr.v1.MapReduce.GetnReduce:input_type -> mr.v1.GetnReduceRequestArgs
	4, // 2: mr.v1.MapReduce.ReportTask:input_type -> mr.v1.ReportTaskArgs
	1, // 3: mr.v1.MapReduce.TaskRequest:output_type -> mr.v1.TaskRequestResponse
	3, // 4: mr.v1.MapReduce.GetnReduce:output_type -> mr.v1.GetnReduceRequestResponse
	5, // 5: mr.v1.MapReduce.ReportTask:output_type -> mr.v1.ReportTaskResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_mr_proto_init() }
func file_api_mr_proto_init() {
	if File_api_mr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequestArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetnReduceRequestArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetnReduceRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTaskArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mr_proto_goTypes,
		DependencyIndexes: file_api_mr_proto_depIdxs,
		MessageInfos:      file_api_mr_proto_msgTypes,
	}.Build()
	File_api_mr_proto = out.File
	file_api_mr_proto_rawDesc = nil
	file_api_mr_proto_goTypes = nil
	file_api_mr_proto_depIdxs = nil
}
