// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: api/mr.proto

package mr_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MapReduceClient is the client API for MapReduce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapReduceClient interface {
	TaskRequest(ctx context.Context, in *TaskRequestArgs, opts ...grpc.CallOption) (*TaskRequestResponse, error)
	GetnReduce(ctx context.Context, in *GetnReduceRequestArgs, opts ...grpc.CallOption) (*GetnReduceRequestResponse, error)
	ReportTask(ctx context.Context, in *ReportTaskArgs, opts ...grpc.CallOption) (*ReportTaskResponse, error)
}

type mapReduceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapReduceClient(cc grpc.ClientConnInterface) MapReduceClient {
	return &mapReduceClient{cc}
}

func (c *mapReduceClient) TaskRequest(ctx context.Context, in *TaskRequestArgs, opts ...grpc.CallOption) (*TaskRequestResponse, error) {
	out := new(TaskRequestResponse)
	err := c.cc.Invoke(ctx, "/mr.v1.MapReduce/TaskRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceClient) GetnReduce(ctx context.Context, in *GetnReduceRequestArgs, opts ...grpc.CallOption) (*GetnReduceRequestResponse, error) {
	out := new(GetnReduceRequestResponse)
	err := c.cc.Invoke(ctx, "/mr.v1.MapReduce/GetnReduce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapReduceClient) ReportTask(ctx context.Context, in *ReportTaskArgs, opts ...grpc.CallOption) (*ReportTaskResponse, error) {
	out := new(ReportTaskResponse)
	err := c.cc.Invoke(ctx, "/mr.v1.MapReduce/ReportTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapReduceServer is the server API for MapReduce service.
// All implementations must embed UnimplementedMapReduceServer
// for forward compatibility
type MapReduceServer interface {
	TaskRequest(context.Context, *TaskRequestArgs) (*TaskRequestResponse, error)
	GetnReduce(context.Context, *GetnReduceRequestArgs) (*GetnReduceRequestResponse, error)
	ReportTask(context.Context, *ReportTaskArgs) (*ReportTaskResponse, error)
	mustEmbedUnimplementedMapReduceServer()
}

// UnimplementedMapReduceServer must be embedded to have forward compatible implementations.
type UnimplementedMapReduceServer struct {
}

func (UnimplementedMapReduceServer) TaskRequest(context.Context, *TaskRequestArgs) (*TaskRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskRequest not implemented")
}
func (UnimplementedMapReduceServer) GetnReduce(context.Context, *GetnReduceRequestArgs) (*GetnReduceRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetnReduce not implemented")
}
func (UnimplementedMapReduceServer) ReportTask(context.Context, *ReportTaskArgs) (*ReportTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTask not implemented")
}
func (UnimplementedMapReduceServer) mustEmbedUnimplementedMapReduceServer() {}

// UnsafeMapReduceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapReduceServer will
// result in compilation errors.
type UnsafeMapReduceServer interface {
	mustEmbedUnimplementedMapReduceServer()
}

func RegisterMapReduceServer(s grpc.ServiceRegistrar, srv MapReduceServer) {
	s.RegisterService(&MapReduce_ServiceDesc, srv)
}

func _MapReduce_TaskRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequestArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).TaskRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mr.v1.MapReduce/TaskRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).TaskRequest(ctx, req.(*TaskRequestArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduce_GetnReduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetnReduceRequestArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).GetnReduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mr.v1.MapReduce/GetnReduce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).GetnReduce(ctx, req.(*GetnReduceRequestArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapReduce_ReportTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapReduceServer).ReportTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mr.v1.MapReduce/ReportTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapReduceServer).ReportTask(ctx, req.(*ReportTaskArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// MapReduce_ServiceDesc is the grpc.ServiceDesc for MapReduce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapReduce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mr.v1.MapReduce",
	HandlerType: (*MapReduceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskRequest",
			Handler:    _MapReduce_TaskRequest_Handler,
		},
		{
			MethodName: "GetnReduce",
			Handler:    _MapReduce_GetnReduce_Handler,
		},
		{
			MethodName: "ReportTask",
			Handler:    _MapReduce_ReportTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mr.proto",
}
